version: "3"

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://localhost:9200/
    volumes:
      - kibana-log:/var/log

volumes:
  kibana-log:
