version: "3"

services:
  
  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-db:
  mongo-configdb:

